export const csvHeaders = {
   deliveryOrders: ["Order Month","Order ID","Order Date","Order Time","Parent Company","Brand","Outlet","Driver Type","Fleet", "Order Status", "Order Type","Payment Method"
   ,"Offer Type","food cost before discount","Subtotal","Savings", "Delivery fee to Customer","Total Amount", "Food Cost After Discount","Contract Commision Standard","Contract Commision UP Driver",
   "Contract Fee Amount UP Driver","Contract Fee Rate Card", "Charge for Commision", "Charge for UP Driver ", "Charge for Card", "Total UP charges", "FC minus Total UP Charges","Contract Merchant Driver Fee", "Merchant Earnings","Issue Scenario 1"
   ,"Issue Scenario 2", "Comments",
   "Successful",
   "Post_Scenario_Subtotal",
   "Post_Scenario_Savings",
   "Post_Scenario_Delivery_Fee_to_Customer",
   "Post_Scenario_Total_Amount",
   "Post_Scenario_Food_Cost_After_Discount",
   "Post_Scenario_Total_UP_Charges",
   "Post_Scenario_Merchant_Earnings",
   "Merchant_Negative_Adjustments",
   "Merchant_Positive_Adjustments",
   "Bee_Negative_Adjustments",
   "Bee_Positive_Adjustments",
   "Cash_Collected_By_Bee",
   "Ref_ID",
   "Outlet_ID",
   "User_ID",
   "Brand_ID",
   "B1G1F_ID",
   "SXGY_ID",
   "Driver_ID",
   "Delivery_Status",
   "Created At",
   "User_Phone_Number",
   "User_Email",
   "User_Name",
   "User_Address",
   "User_Latitude",
   "User_Longitude",
   "Outlet_Latitude",
   "Outlet_Longitude"]
}
